apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-national-transfer-prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:National-Transfer/National-Transfer-manifests.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespaces: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
